### PR TITLE
[14.0] Migration of project_task_report

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module project_task_report.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by chusamo — APPROVED** [review]
LGTM Functional Review

**Review by dalonsod — APPROVED** [review]
Locally tested 👍 
Maybe task report & task chatter report inheritance could be improved in order to prevent code repeating, but it could be achieved in a later PR.

**Comment by dalonsod** [comment]
Hello @dreispt is this PR ready to be merged? Thanks!

**Pull request merged**
