### PR TITLE
[16.0][MIG] migration of module project_task_report

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module project_task_report.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by cvinh — CHANGES_REQUESTED** [review]
works well
please check pre-commit

**Comment by cvinh** [comment]
Also I improved the reports here https://github.com/Jarsa-dev/project-reporting/pull/1

**Comment by alan196** [comment]
@cvinh I apply you MR, rebased an fix pre-commit issues, could you help me to review 🙏

**Review by cvinh — APPROVED** [review]
We use it in production for months

**Review by rvalyi — APPROVED** [review]

**Comment by rvalyi** [comment]
/ocabot merge nobump

(I also approved the v15 PR BTW)

**Pull request merged**
