### PR TITLE
[11.0][FIX] project_task_report: some users are not able to print tracking values.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
But they are able to see them in the chatter widget.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why don't you have permissions? That object doesn't have special ACLs AFAIK.

**Comment by LoisRForgeFlow** [comment]
Only admin group have access to it in v11: https://github.com/odoo/odoo/blob/11.0/addons/mail/security/ir.model.access.csv#L26

**Comment by pedrobaeza** [comment]
Ahm, OK, I though it as the other way.

**Review by pedrobaeza — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Thanks!

**Pull request merged**
