### PR TITLE
[12.0][ADD] project_task_timesheet_report: add new module to print report with detailed timesheets

### PR DESCRIPTION
**Pull request by alan196**
This PR adds the ability to print the task report with timesheets.
This PR is ready to review.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
I tested on my computer. Everything is OK

image

I also looked at the code
Thank you for this new module

**Review by lmgr0312 — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Comment by alan196** [comment]
@dreispt I rebased and fix the issue, now is ready to merge.

**Pull request merged**
