### PR TITLE
[13.0][MIG] Migration of project task report to V13

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module project_task_report and it's functionalities from Odoo 12.0 to 13.0. I've checked if the all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated necessary documentation

### Further comments

I have added the PR https://github.com/OCA/project-reporting/pull/36 in this migration.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
I tested on my computer : 
image

Everything works fine
Thank you for this migration

**Review by lmgr0312 — APPROVED** [review]
LGTM!

**Review by dreispt — APPROVED** [review]

**Pull request merged**
